debug: false
server:
  port: 8080
  
spring:
  application:
    name: rest-api-demo
    version: v1.0.0
    description: A simple REST API demo applications, which performs CRUD operations
  datasource:
    url: jdbc:mysql://localhost:3306/employee_details?useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    user:
      name: user
      password: password@123
